### ISSUE TITLE
Compilation errors!

### ISSUE THREAD

**Issue by Graywd** [cstack/db_tutorial#12]
I get some errors below when I try to compile the code in "Part 3 - An In-Memory, Append-Only, Singe-Table Database".
...
db.c:38:7: error: unknown type name ‘uint32_t’
db.c:42:7: error: variably modified ‘username’ at file scope
....

This is  my environment, gcc version 5.4.0 on ubuntu 16.04.2 LTS. 
Could you tell me the gcc version of  you ?

Thanks.

**Comment by cstack** [comment]
Hi, I haven't put a lot of effort into portability yet, so sorry about the errors.

I've been developing on OSX 10.12.6 . When I run `gcc -v` I get:

```
gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by whtsky** [comment]
actually, the `gcc` on OSX is an alias to `clang`.
faced the same problem trying to compile with gcc 5 & gcc 6. Switching to clang solved the problem.

**Comment by Graywd** [comment]
@whtsky 
Now everything is fine when I changed to clang and included a header "<stdint.h>".
Thank you very much.
