### ISSUE TITLE
Translation db tutorial articles

### ISSUE THREAD

**Issue by japinli** [cstack/db_tutorial#22]
@cstack Could I translate these articles into Chinese?

**Comment by cstack** [comment]
Hi @japinli , you're free to translate these articles in a different repo or on your own site if you link back to this project, but if you want to include the translated articles in this project, I'd like to set up some kind of system to manage translations as new articles are written or changes are made to old articles (maybe this? https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin)

**Comment by japinli** [comment]
@cstack Thanks for your sharing. For now, I just create a new repo to store the translation.

Best regards!
