### ISSUE TITLE
Could you add a license file of the source code?

### ISSUE THREAD

**Issue by c-bata** [cstack/db_tutorial#26]
Hi! Thanks to publish this interesting tutorial. I learned a lot from this tutorial.

BTW, I try to implement this database in Rust (and Python3 for testing). And I wanna publish the source codes on my github account. But the license file is not found in this repository. Could you add a license file? If you don't allow it, I close this issue and I don't publish the source codes.

Thanks.

**Comment by cstack** [comment]
Sure thing, I added a license. Feel free to send me a link when you publish your port!

**Comment by sctowne1** [comment]
There is none. This was developed through a textbook example I found online
a while back. Do with it what you want.

**Comment by c-bata** [comment]
@cstack I published the Rust port of db_tutorial. Thanks.
https://github.com/c-bata/db_tutorial
