### ISSUE TITLE
Storing code per tutorial part

### ISSUE THREAD

**Issue by ikraduya** [cstack/db_tutorial#36]
what if the code is also stored per part, 
so that it makes it easier to validate the correctness of  program per part tutorial?

btw, thanks for the very nice tutorial :+1:

**Comment by cstack** [comment]
That's actually a great idea. I'll keep it in mind.

**Comment by ikraduya** [comment]
I could help to provide the code, since I working on this tutorial too

may I?

**Comment by cstack** [comment]
Sure, feel free to open a PR!
