### ISSUE TITLE
Structures ending with _t

### ISSUE THREAD

**Issue by clintonyeb** [cstack/db_tutorial#4]
I presume you have a lot of coding experience. I don't know why but you append all the names of your structures with _t, example:
 ```
enum MetaCommandResult_t {
  META_COMMAND_SUCCESS,
  META_COMMAND_UNRECOGNIZED_COMMAND
};
typedef enum MetaCommandResult_t MetaCommandResult;
```

and then later redefine it. 

Is there any advantage to doing this?

**Comment by cstack** [comment]
Hi,

The reason I do this is the compiler I'm using requires that whenever you reference a struct or enum you use the `struct` or `enum` keyword. (e.g. `enum MetaCommandResult_t`). I immediately create a typedef so I don't have to use the keyword.

**Comment by clintonyeb** [comment]
Thank you for your awesome work!. I think you can close the issue now :smile:

**Comment by shubham1172** [comment]
Hey, I wonder why can't we just do this
```c
typedef struct {
    char* buffer;
    size_t buffer_length;
    size_t input_length;
} InputBuffer;
```

Will save an extra line of code and will be as efficient I guess.

**Comment by cstack** [comment]
@shubham1172 Awesome! I went ahead and made that change https://github.com/cstack/db_tutorial/pull/37
