### ISSUE TITLE
Have you finished this tutorial?

### ISSUE THREAD

**Issue by Ynjxsjmh** [cstack/db_tutorial#46]
After reading this tutorial, I notice that the tutorial seems not over yet.

So will you finish the remaining part?

**Comment by cstack** [comment]
I'd like to but I just don't have time right now.

**Comment by i0Ek3** [comment]
@cstack So, this tutorial is awesome, I really hope it can be continued. Can you introduce the next plan or what contents of the next?  Just like Part 14. Splitting the Internal Nodes? And I found this: https://play.google.com/books/reader?id=9Z6IQQnX1JEC&hl=zh_CN&pg=GBS.PR9, I mean, we still have many works to do, right?  If I want to continued that, what should I do, can you give some advice? Thanks a lot.

**Comment by RaissaNa** [comment]
Hi, the tutorial is really awesome. Have you finshed it by now ?

**Comment by jinxcrazy** [comment]
Hi, found it quite helpful. Will you continue to update it :)
