### ISSUE TITLE
Pull requests about translation

### ISSUE THREAD

**Issue by imsoo** [cstack/db_tutorial#52]
@cstack Hi,
First, Thank you for your awesome work!
I've translated the article into korean. this [repo](https://github.com/imsoo/db_tutorial/tree/kor)
If  translated version include in this project, that would be great.
Could I pull requests to this repo?

Related issues : #22, #35

* ***Example of result***

| ***index*** | ***part*** | 
|:--------:|:--------:|
| ![index](https://user-images.githubusercontent.com/11255376/71642659-2acce400-2cf2-11ea-953f-55ec9c275938.JPG) | ![part](https://user-images.githubusercontent.com/11255376/71642661-2d2f3e00-2cf2-11ea-91c0-f9b0790d0cdc.JPG) |

**Comment by cstack** [comment]
That's awesome! Thank you!

Please open a PR. I definitely won't be able to keep the translation up to date if there are any changes or additions to the tutorial, but including the translation is better than nothing.
