### ISSUE TITLE
Can anyone tell me why are we doing serialize_row and deserialize_row?

### ISSUE THREAD

**Issue by terra9** [cstack/db_tutorial#61]
Is it to copy the row_to_insert pointer  to new pointer?

**Comment by WangTingZheng** [comment]
To copy different rows to one page, before that, you must serialize struct row to same format : void *.  If you want,  base on this, you can write page to disk conveniently.

**Comment by rakshitraj** [comment]
Could someone offer more clarity on this? @cstack
