### ISSUE TITLE
Can i continue this awesome project, dear cstack?

### ISSUE THREAD

**Issue by faceless00** [cstack/db_tutorial#84]
I have learned a lot from this tutorial, and i thought part 13 will complete this project.   
Emm... So can i continue this project? For instance, Part 14?   
If you agree, can you give me some advice?   
I have translate all parts of this article in chinese on my github pages( I have said the original article is  on your website).   
😤😤

**Comment by cstack** [comment]
Please feel free to continue the tutorial on your own!

**Comment by Ashvith10** [comment]
@cstack part 15 of the page does not mention how we can be improving the database, or at least the areas we should look into. Would you mind adding details about that?

**Comment by lizardwizardd** [comment]
> part 15 of the page does not mention how we can be improving the database, or at least the areas we should look into. Would you mind adding details about that?

Add support for multiple tables, implement UPDATE and soft deletion of rows. These are simple improvements that don't require big structural changes
